# industry_config.py — Configuration for each industry dataset

INDUSTRIES = {
    'telecom': {
        'name'         : 'Telecom',
        'icon'         : '📡',
        'description'  : 'Predict which telecom customers will cancel their subscription',
        'file'         : 'datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv',
        'file_type'    : 'csv',
        'sheet'        : None,
        'target'       : 'Churn',
        'target_map'   : {'Yes': 1, 'No': 0},
        'drop_cols'    : ['customerID'],
        'model_file'   : 'models/telecom_model.pkl',
        'scaler_file'  : 'models/telecom_scaler.pkl',
        'features_file': 'models/telecom_features.pkl',
    },
    'banking': {
        'name'         : 'Banking',
        'icon'         : '🏦',
        'description'  : 'Predict which bank customers will close their account',
        'file'         : 'datasets/Churn_Modelling.csv',
        'file_type'    : 'csv',
        'sheet'        : None,
        'target'       : 'Exited',
        'target_map'   : None,
        'drop_cols'    : ['RowNumber', 'CustomerId', 'Surname'],
        'model_file'   : 'models/banking_model.pkl',
        'scaler_file'  : 'models/banking_scaler.pkl',
        'features_file': 'models/banking_features.pkl',
    },
    'ecommerce': {
        'name'         : 'E-Commerce',
        'icon'         : '🛒',
        'description'  : 'Predict which online store customers will stop buying',
        'file'         : 'datasets/E Commerce Dataset.xlsx',
        'file_type'    : 'xlsx',
        'sheet'        : 'E Comm',
        'target'       : 'Churn',
        'target_map'   : None,
        'drop_cols'    : ['CustomerID'],
        'model_file'   : 'models/ecommerce_model.pkl',
        'scaler_file'  : 'models/ecommerce_scaler.pkl',
        'features_file': 'models/ecommerce_features.pkl',
    }
}